/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as EntryCheckoutRouteImport } from './routes/entry-checkout'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffStatisticsRouteImport } from './routes/staff/statistics'
import { Route as StaffScanRouteImport } from './routes/staff/scan'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryCheckoutRoute = EntryCheckoutRouteImport.update({
  id: '/entry-checkout',
  path: '/entry-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStatisticsRoute = StaffStatisticsRouteImport.update({
  id: '/staff/statistics',
  path: '/staff/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffScanRoute = StaffScanRouteImport.update({
  id: '/staff/scan',
  path: '/staff/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/admin/calendar',
  path: '/admin/calendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/entry-checkout': typeof EntryCheckoutRoute
  '/my-profile': typeof MyProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/statistics': typeof StaffStatisticsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/entry-checkout': typeof EntryCheckoutRoute
  '/my-profile': typeof MyProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/statistics': typeof StaffStatisticsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/entry-checkout': typeof EntryCheckoutRoute
  '/my-profile': typeof MyProfileRoute
  '/schedule': typeof ScheduleRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/statistics': typeof StaffStatisticsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/entry-checkout'
    | '/my-profile'
    | '/schedule'
    | '/admin/calendar'
    | '/admin/staff'
    | '/admin/statistics'
    | '/staff/scan'
    | '/staff/statistics'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/entry-checkout'
    | '/my-profile'
    | '/schedule'
    | '/admin/calendar'
    | '/admin/staff'
    | '/admin/statistics'
    | '/staff/scan'
    | '/staff/statistics'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/entry-checkout'
    | '/my-profile'
    | '/schedule'
    | '/admin/calendar'
    | '/admin/staff'
    | '/admin/statistics'
    | '/staff/scan'
    | '/staff/statistics'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  EntryCheckoutRoute: typeof EntryCheckoutRoute
  MyProfileRoute: typeof MyProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  StaffScanRoute: typeof StaffScanRoute
  StaffStatisticsRoute: typeof StaffStatisticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry-checkout': {
      id: '/entry-checkout'
      path: '/entry-checkout'
      fullPath: '/entry-checkout'
      preLoaderRoute: typeof EntryCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/statistics': {
      id: '/staff/statistics'
      path: '/staff/statistics'
      fullPath: '/staff/statistics'
      preLoaderRoute: typeof StaffStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/scan': {
      id: '/staff/scan'
      path: '/staff/scan'
      fullPath: '/staff/scan'
      preLoaderRoute: typeof StaffScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  EntryCheckoutRoute: EntryCheckoutRoute,
  MyProfileRoute: MyProfileRoute,
  ScheduleRoute: ScheduleRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  StaffScanRoute: StaffScanRoute,
  StaffStatisticsRoute: StaffStatisticsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
