@startuml FitnessApp

!pragma ratio 0.80

 skinparam linetype polyline
' skinparam linetype ortho

left to right direction

' Actors:
actor "Admin" as admin
actor "Staff" as staff
actor "Customer" as customer

' Generalizations:
staff -[norank]-|> admin


' System boundary:
rectangle "FitnessApp" as fitnessApp {
    usecase "Register" as register
    usecase "Log in" as login
    usecase "Reset Password" as resetPassword
    usecase "Register lecture" as registerLecture
    usecase "Send Confirmation Email" as confirmationEmail
    usecase "Unregister lecture" as unregisterLecture
    usecase "Buy subscription" as buySubscription
    usecase "Stop subscription" as stopSubscription
    usecase "Change contact information" as changeContact
    usecase "Log in\n--\n**extension points**\nOAuth" as login
    usecase "Log in via OAuth" as oauthLogin

    usecase "CRUD Lecture" as crudLecture
    usecase "CRUD Customer" as crudCustomer
    usecase "Check lecture's roster" as checkRoster
    usecase "Mark lecture's attendence" as markAttendence
    usecase "View Payment history" as viewPaymentHistory
    
    usecase "CRUD Staff" as crudStaff
    usecase "View System analytics" as viewAnalytics
    }

' Includes, extends:

register ..> confirmationEmail : <<include>>
resetPassword ..> confirmationEmail : <<include>>
registerLecture ..> confirmationEmail : <<include>>
unregisterLecture ..> confirmationEmail : <<include>>
buySubscription ..> confirmationEmail : <<include>>
oauthLogin .up.> login : <<extend>>

' Associations between actors and use cases:
customer -- register
customer -- login
customer -- resetPassword
customer -- registerLecture
customer -- unregisterLecture
customer -- buySubscription
customer -- stopSubscription
customer -- changeContact

staff -- crudLecture
staff -- crudCustomer
staff -- checkRoster
staff -- markAttendence
staff -- viewPaymentHistory

admin -- crudStaff
admin -- viewAnalytics

@enduml
